### PR TITLE
docs deployment

### PR DESCRIPTION
**Pull request by rkurchin**
Making a few tweaks to @thazhemadam's excellent start and then will merge this in and deploy our real docs so we can jettison the wiki ones! 😁

### CODE REVIEW

**Comment by thazhemadam** [comment]
Just a reminder to change the CI script's branch for the documentation workflow.

**Comment by rkurchin** [comment]
Haha thanks, just did that, then realized I hadn’t set up the gh-pages in the repo and I think I might have to trigger the build again for it to actually go…almost there!

Best,
Rachel Kurchin, PhD
MolSSI Postdoctoral Fellow
Carnegie Mellon Mechanical Engineering and Materials Science
rkurchin.github.io

**Comment by rkurchin** [comment]
Still to do here:
- [ ] update things for restructure
- [ ] finish changelog
- [ ] add some examples

**Comment by rkurchin** [comment]
@thazhemadam, I'm inclined to just merge this if you think the general skeleton is okay. It's getting painful to rebase because it's kind of old. We can fill in the other gaps in a smaller PR.

**Comment by thazhemadam** [comment]
> I'm inclined to just merge this if you think the general skeleton is okay

@rkurchin the overall skeleton lgtm.

> It's getting painful to rebase because it's kind of old.

I concur. This PR is painfully behind `main` and the `restructure` as is.

> We can fill in the other gaps in a smaller PR.

Just a note here that we're yet to set up doctests, and some more docstrings too.

**Review by thazhemadam — COMMENTED** [review]
LGTM

**Pull request merged**
