### PR TITLE
Add more docs

### PR DESCRIPTION
**Pull request by thazhemadam**

### CODE REVIEW

**Comment by thazhemadam** [comment]
At this point, I'm just writing down stuff I've made notes of (both mental, and tangible), so I'm not really particular about having things organized the way they are currently (or even having all this content finally make it into the docs for that matter).

**Review by rkurchin — COMMENTED** [review]
These look great to me! When I build the docs locally, however, it's throwing a lot of missing docstrings errors...but this might still be my weird local configuration issue, because when I actually import this version of the package, I can see those docstrings, so I'm guessing it's fine?

**Comment by rkurchin** [comment]
@thazhemadam there are probably still things we could add in docs but I'm fine with merging this nowish, especially since there have been a couple people expressing interest in the package after JuliaCon, so having the tutorial up would be good.

Thoughts?

**Comment by rkurchin** [comment]
I think this resolves #3

**Comment by thazhemadam** [comment]
I agree. I think atm there's enough content in the docs to get things up and running.
We can always open up a new PR anyways when we want to add more content. Merging this PR.

**Pull request merged**
